{{ config(
    materialized='view',
    schema = 'STAGING')}}
SELECT
    TRANSACTION_ID,
    CAST(TRANSACTION_DATE AS DATE) AS TRANSACTION_DATE,
    ACCOUNT_ID,
    SECURITY_ID,
    ADVISOR_ID,
    TRANSACTION_TYPE,
    QUANTITY,
    PRICE,
    TRADE_VALUE,
    BROKERAGE_FEE,
    TAX_AMOUNT,
    SOURCE_SYSTEM,
    BATCH_ID,
    CAST(LOAD_DATE AS DATE) AS LOAD_DATE,
    RECORD_CREATED_TS,
    RECORD_UPDATED_TS
FROM {{ source('raw', 'RAW_TRANSACTIONS')}}