--

SELECT * FROM FINANCIAL_DWH.MART.DIM_ACCOUNTS
ORDER BY ACCOUNT_ID;


SELECT * FROM FINANCIAL_DWH.MART.DIM_ADVISORS
ORDER BY ADVISOR_ID;


SELECT * FROM FINANCIAL_DWH.MART.DIM_CUSTOMERS
ORDER BY CUSTOMER_ID;


SELECT * FROM FINANCIAL_DWH.MART.DIM_SECURITIES
ORDER BY SECURITY_ID;