--Accounts dim table

SELECT * FROM FINANCIAL_DWH.MART.DIM_ACCOUNTS
ORDER BY ACCOUNT_ID;

--Advisors dim table

SELECT * FROM FINANCIAL_DWH.MART.DIM_ADVISORS
ORDER BY ADVISOR_ID;

--Customers dim table

SELECT * FROM FINANCIAL_DWH.MART.DIM_CUSTOMERS
ORDER BY CUSTOMER_ID;

--Securities dim table

SELECT * FROM FINANCIAL_DWH.MART.DIM_SECURITIES
ORDER BY SECURITY_ID;
