USE ROLE ACCOUNTADMIN;
USE DATABASE FINANCIAL_DWH;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE S3_STAGE
URL = 's3://AWS_bucket_NAME/'
STORAGE_INTEGRATION = S3_INT
FILE_FORMAT = CSV_FORMAT;

LIST @S3_STAGE;

--SNOWPIPE

--ADVISORS PIPE

CREATE OR REPLACE PIPE RAW.ADVISORS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO RAW.RAW_ADVISORS
FROM(
    SELECT
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
    FROM @S3_STAGE/advisors/
)
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

--CUSTOMERS PIPE

CREATE OR REPLACE PIPE RAW.CUSTOMERS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO RAW.RAW_CUSTOMERS
FROM(
    SELECT
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
    FROM @S3_STAGE/customer/
)
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

--ACCOUNTS PIPE

CREATE OR REPLACE PIPE RAW.ACCOUNTS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO RAW.RAW_ACCOUNTS
FROM(
    SELECT
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
    FROM @S3_STAGE/accounts/
)
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

--SECURITIES PIPE

CREATE OR REPLACE PIPE RAW.SECURITIES_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO RAW.RAW_SECURITIES
FROM(
    SELECT
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
    FROM @S3_STAGE/security/
)
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);


--TRANSACTION PIPE


CREATE OR REPLACE PIPE RAW.TRANSACTIONS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO RAW.RAW_TRANSACTIONS
FROM(
    SELECT
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
    FROM @S3_STAGE/transactions/
)
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

SHOW PIPES;

ALTER PIPE RAW.ADVISORS_PIPE REFRESH;

ALTER PIPE RAW.CUSTOMERS_PIPE REFRESH;

ALTER PIPE RAW.ACCOUNTS_PIPE REFRESH;

ALTER PIPE RAW.SECURITIES_PIPE REFRESH;

ALTER PIPE RAW.TRANSACTIONS_PIPE REFRESH;
