SELECT * FROM FINANCIAL_DWH.MART.ACCOUNT_HISTORY
ORDER BY ACCOUNT_ID;


SELECT * FROM FINANCIAL_DWH.MART.ADVISORS_HISTORY
ORDER BY ADVISOR_ID;


SELECT * FROM FINANCIAL_DWH.MART.CUSTOMER_HISTORY
ORDER BY CUSTOMER_ID, VALID_FROM;


SELECT * FROM FINANCIAL_DWH.MART.SECURITIES_HISTORY
ORDER BY SECURITY_ID;