CREATE OR REPLACE DATABASE FINANCIAL_DWH;

USE DATABASE FINANCIAL_DWH;

CREATE OR REPLACE SCHEMA RAW;

CREATE OR REPLACE SCHEMA STAGING;

CREATE OR REPLACE SCHEMA MART;

CREATE OR REPLACE WAREHOUSE FIN_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE
INITIALLY_SUSPENDED=TRUE;

USE WAREHOUSE FIN_WH;

USE SCHEMA RAW;


CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER=','
SKIP_HEADER=1
FIELD_OPTIONALLY_ENCLOSED_BY='"'
EMPTY_FIELD_AS_NULL = TRUE
TRIM_SPACE=TRUE;


USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'AWS_Role_ARN'
STORAGE_ALLOWED_LOCATIONS = (
    's3://AWS_BUCKET/'
);

DESC INTEGRATION S3_INT;

