SELECT * FROM FINANCIAL_DWH.SNAPSHOTS.CUSTOMER_SNAPSHOT
order by CUSTOMER_ID, dbt_valid_to desc;


SELECT * FROM FINANCIAL_DWH.SNAPSHOTS.ACCOUNTS_SNAPSHOT
ORDER BY ACCOUNT_ID;


SELECT * FROM FINANCIAL_DWH.SNAPSHOTS.ADVISORS_SNAPSHOT
ORDER BY ADVISOR_ID;


SELECT * FROM FINANCIAL_DWH.SNAPSHOTS.SECURITIES_SNAPSHOT
ORDER BY SECURITY_ID;