SELECT * FROM FINANCIAL_DWH.STAGING.STG_ACCOUNTS;

SELECT * FROM FINANCIAL_DWH.STAGING.STG_ADVISORS;

SELECT * FROM FINANCIAL_DWH.STAGING.STG_CUSTOMERS;

SELECT * FROM FINANCIAL_DWH.STAGING.STG_SECURITIES;

SELECT * FROM FINANCIAL_DWH.STAGING.STG_TRANSACTIONS;