--advisor performance

SELECT * FROM FINANCIAL_DWH.MART.MART_ADVISOR_PERFORMANCE
ORDER BY ADVISOR_ID;

--customer info

SELECT * FROM FINANCIAL_DWH.MART.MART_CUSTOMER_PORTFOLIO
ORDER BY CUSTOMER_ID;

SELECT * FROM FINANCIAL_DWH.MART.MART_CUSTOMER_ACTIVITY
ORDER BY CUSTOMER_ID;

--daily transactions

SELECT * FROM FINANCIAL_DWH.MART.MART_DAILY_TRANSACTIONS;

--security information

SELECT * FROM FINANCIAL_DWH.MART.MART_SECURITY_PERFORMANCE
ORDER BY security_id;

--branch insights

SELECT * FROM FINANCIAL_DWH.MART.MART_BRANCH_SUMMARY;
