USE DATABASE FINANCIAL_DWH;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW_ADVISORS(
    ADVISOR_ID VARCHAR,
    ADVISOR_NAME VARCHAR,
    BRANCH VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    HIRE_DATE DATE,
    STATUS VARCHAR,

    SOURCE_SYSTEM VARCHAR,
    BATCH_ID VARCHAR,
    LOAD_DATE DATE,
    RECORD_CREATED_TS TIMESTAMP_NTZ,
    RECORD_UPDATED_TS TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE RAW_ACCOUNTS (
    ACCOUNT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    ACCOUNT_TYPE VARCHAR,
    OPEND_DATE VARCHAR,
    BRANCH VARCHAR,
    CURRENCY VARCHAR,
    STATUS VARCHAR,
    SOURCE_SYSTEM VARCHAR,
    BATCH_ID VARCHAR,
    LOAD_DATE VARCHAR,
    RECORD_CREATED_TS TIMESTAMP_NTZ,
    RECORD_UPDATED_TS TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE RAW_SECURITIES(
    SECURITY_ID VARCHAR,
    TICKER VARCHAR,
    SECURITY_NAME VARCHAR,
    ASSET_CLASS VARCHAR,
    SECTOR VARCHAR,
    CURRENCY VARCHAR,
    EXCHANGE VARCHAR,
    STATUS VARCHAR,
    SOURCE_SYSTEM VARCHAR,
    BATCH_ID VARCHAR,
    LOAD_DATE DATE,
    RECORD_CREATED_TS TIMESTAMP_NTZ,
    RECORD_UPDATED_TS TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE RAW_TRANSACTIONS(
    TRANSACTION_ID VARCHAR,
    TRANSACTION_DATE VARCHAR,
    ACCOUNT_ID VARCHAR,
    SECURITY_ID VARCHAR,
    ADVISOR_ID VARCHAR,
    TRANSACTION_TYPE VARCHAR,
    QUANTITY NUMBER(18, 2),
    PRICE NUMBER(18, 2),
    TRADE_VALUE NUMBER(18, 2),
    BROKERAGE_FEE NUMBER(18, 2),
    TAX_AMOUNT NUMBER(18, 2),
    SOURCE_SYSTEM VARCHAR,
    BATCH_ID VARCHAR,
    LOAD_DATE DATE,
    RECORD_CREATED_TS TIMESTAMP_NTZ,
    RECORD_UPDATED_TS TIMESTAMP_NTZ
);



CREATE OR REPLACE TABLE RAW_CUSTOMERS(
    CUSTOMER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    DOB DATE,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    ADVISOR_ID VARCHAR,
    RISK_PROFILE VARCHAR,
    ANNUAL_INCOME NUMBER(18, 2),
    STATUS VARCHAR,
    SOURCE_SYSTEM VARCHAR,
    BATCH_ID VARCHAR,
    LOAD_DATE VARCHAR,
    RECORD_CREATED_TS TIMESTAMP_NTZ,
    RECORD_UPDATED_TS TIMESTAMP_NTZ
);




SELECT
    CUSTOMER_ID,
    COUNT(*)
FROM FINANCIAL_DWH.RAW.RAW_CUSTOMERS
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;


SELECT COUNT(*) FROM FINANCIAL_DWH.RAW.RAW_ACCOUNTS;
SELECT COUNT(*) FROM FINANCIAL_DWH.RAW.RAW_ADVISORS;
SELECT COUNT(*) FROM FINANCIAL_DWH.RAW.RAW_SECURITIES;
SELECT COUNT(*) FROM FINANCIAL_DWH.RAW.RAW_TRANSACTIONS;

