{{ config(materialized='table')}}

WITH DAILY_TRANSACTION AS(
    SELECT
        TRANSACTION_DATE,
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        QUANTITY,
        TRADE_VALUE,
        BROKERAGE_FEE,
        TAX_AMOUNT
    FROM {{ ref('fact_transactions') }}
)SELECT
    TRANSACTION_DATE,
    COUNT(DISTINCT TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
    COALESCE(SUM(
        CASE 
            WHEN UPPER(TRANSACTION_TYPE) = 'BUY'
            THEN TRADE_VALUE
            ELSE 0
    END), 0
    ) AS TOTAL_BUY_VALUE,

    COALESCE(SUM(
        CASE
            WHEN UPPER(TRANSACTION_TYPE) = 'SELL'
            THEN TRADE_VALUE
            ELSE 0
    END), 0
    ) AS TOTAL_SELL_VALUE,

    COALESCE(SUM(TRADE_VALUE), 0) AS TOTAL_TRADE_VALUE,

    MAX(TRADE_VALUE) AS LARGEST_TRADE,
    MIN(TRADE_VALUE) AS SMALLEST_TRADE,
    AVG(TRADE_VALUE) AS AVG_TRADE_VALUE
FROM DAILY_TRANSACTION
GROUP BY TRANSACTION_DATE